#!/usr/bin/env node
/**
 * Teamind Setup — Initialize the SQLite database with vector search tables.
 *
 * Usage:
 *   node setup.js                     # default: ./teamind.db
 *   DB_PATH=/data/gm.db node setup.js # custom path
 */

const Database = require('better-sqlite3');
const path = require('path');

const DB_PATH = process.env.DB_PATH || path.join(__dirname, 'teamind.db');

console.log(`🧠 Teamind Setup — initializing ${DB_PATH}`);

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

db.exec(`
  -- Channels being indexed
  CREATE TABLE IF NOT EXISTS channels (
    channel_id   TEXT PRIMARY KEY,
    channel_name TEXT,
    platform     TEXT DEFAULT 'slack',  -- slack | telegram | discord
    added_at     TEXT DEFAULT (datetime('now')),
    last_indexed TEXT
  );

  -- Individual messages
  CREATE TABLE IF NOT EXISTS messages (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id   TEXT NOT NULL,
    thread_ts    TEXT,           -- thread parent ts (NULL if top-level non-thread)
    message_ts   TEXT NOT NULL,  -- unique message timestamp
    user_id      TEXT,
    username     TEXT,
    text         TEXT,
    created_at   TEXT,
    embedding    BLOB,           -- float32 array as raw bytes
    UNIQUE(channel_id, message_ts),
    FOREIGN KEY (channel_id) REFERENCES channels(channel_id)
  );

  -- Thread summaries (generated by LLM)
  CREATE TABLE IF NOT EXISTS thread_summaries (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id   TEXT NOT NULL,
    thread_ts    TEXT NOT NULL,
    title        TEXT,
    summary      TEXT,
    thread_type  TEXT,           -- decision | bug_fix | brainstorm | status_update | qa | casual | announcement
    key_points   TEXT,           -- JSON array
    participants TEXT,           -- JSON array [{name, role}]
    open_items   TEXT,           -- JSON array [{item, assignee, deadline}]
    msg_count    INTEGER,
    created_at   TEXT,
    last_msg_at  TEXT,
    embedding    BLOB,           -- float32 array for summary
    UNIQUE(channel_id, thread_ts),
    FOREIGN KEY (channel_id) REFERENCES channels(channel_id)
  );

  -- Indexing state (cursor tracking)
  CREATE TABLE IF NOT EXISTS index_state (
    channel_id   TEXT PRIMARY KEY,
    last_ts      TEXT,           -- last message ts successfully indexed
    last_run     TEXT,
    FOREIGN KEY (channel_id) REFERENCES channels(channel_id)
  );

  -- Indexes for fast queries
  CREATE INDEX IF NOT EXISTS idx_messages_channel_thread ON messages(channel_id, thread_ts);
  CREATE INDEX IF NOT EXISTS idx_messages_created ON messages(created_at);
  CREATE INDEX IF NOT EXISTS idx_threads_channel ON thread_summaries(channel_id);
  CREATE INDEX IF NOT EXISTS idx_threads_type ON thread_summaries(thread_type);
  CREATE INDEX IF NOT EXISTS idx_threads_last_msg ON thread_summaries(last_msg_at);
`);

console.log('✅ Database initialized successfully');
console.log(`   Tables: channels, messages, thread_summaries, index_state`);

// Show stats if DB already has data
const stats = {
  channels: db.prepare('SELECT COUNT(*) as n FROM channels').get().n,
  messages: db.prepare('SELECT COUNT(*) as n FROM messages').get().n,
  threads: db.prepare('SELECT COUNT(*) as n FROM thread_summaries').get().n,
};
if (stats.messages > 0) {
  console.log(`   Data: ${stats.channels} channels, ${stats.messages} messages, ${stats.threads} thread summaries`);
}

db.close();
